import BaseLayout from "@/layouts/base-layout";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Zepto",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <main>
        <BaseLayout>
          {children}
        </BaseLayout>
      </main>
    </html>
  );
}
